### ISSUE TITLE
Add Lotto rules documentation to public navigation bar

### ISSUE THREAD

**Issue by jujaga** [charlieman/ice-lotto-meteor#13]
Copying the rules out from our forum and applying them onto the app itself may raise exposure and ease of entry for newcomers. We'd have to make the rules page viewable without an account for it to be effective. Thoughts @charlieman?

**Comment by charlieman** [comment]
Yes, we can add it as a link in the top menu.

**Comment by jujaga** [comment]
https://github.com/charlieman/ice-lotto-meteor/commit/f8701365e7ec40f091db4d661a3f45cf5d650451
