### ISSUE TITLE
Log panel has highlighted rows after tier rows have a winner

### ISSUE THREAD

**Issue by jujaga** [charlieman/ice-lotto-meteor#16]
Looks like unexpected behavior. Check the deployed server's lotto log from 5/27 -> you'll notice a bunch of player names highlighted if they won at least one item from the tiers. I suspect it's a template sharing issue.

**Comment by charlieman** [comment]
Yes, since we are reusing the same template it highlights the winners. We could add a variable to the template to determine if we don't want to highlight the winning entry, we should also hide the winner text in the third column if we are not highlighting it.

**Comment by charlieman** [comment]
Done in 6172eddfe61. Let me know if that's enough before closing this issue.

**Comment by jujaga** [comment]
Looks like everything looks good on this now. I separated the winner and admin stuff to separate columns and have the columns only show if necessary.
