### ISSUE TITLE
Log Modal rows should highlight with yellow when selected

### ISSUE THREAD

**Issue by jujaga** [charlieman/ice-lotto-meteor#18]
Increases readability at a glance.

**Comment by jujaga** [comment]
https://github.com/charlieman/ice-lotto-meteor/commit/3ff6378214ded8b430b1f6740ea4cb916679e7e5 This commit is partially along the lines of this enhancement as well.

**Comment by charlieman** [comment]
This can't be done with pure CSS because you can't select a parent of an element. [In the future](http://stackoverflow.com/a/1014958) there will be a :has pseudoselector so we could change this with something like:

```
table-log tr:has(input[type="checkbox"]:checked) {
  background: yellow;
}
```
